name: Build luci-app-netmon

on:
  workflow_dispatch:
    inputs:
      releases_branch:
        description: "Select the releases branch"
        required: false
        default: "openwrt-24.10"
        type: choice
        options:
          - openwrt-24.10
          - openwrt-21.02
          - openwrt-22.03
          - openwrt-23.05
          - SNAPSHOT
      letak:
        description: 'Letak folder package'
        required: false
        default: 'tema-mods/luci-app-netmon'
        type: string 
      nama:
        description: 'Nama package'
        required: true
        default: 'luci-app-netmon'
        type: string  
      changelog:
        description: 'Changelog'
        required: false
        default: '-'
        type: string
      url:
        description: 'Repo URL'
        required: false
        default: 'https://github.com/Dirgha80/tema-mods'
        type: string     
  push:
    tags:
      - "v*"

env:
  PACKAGE_NAME: ${{ inputs.nama }}

jobs:
  get-version:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    outputs:
      version: ${{ steps.version.outputs.version }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 1
          ref: ${{ github.ref_name }}

      - name: Extract version
        id: version
        run: |
          VERSION=$(grep 'PKG_VERSION:=' ${{ inputs.nama }}/Makefile | awk -F '=' '{print $2}' | tr -d ' ')
          echo "version=${VERSION}" >> $GITHUB_OUTPUT
          echo "New Version: ${VERSION}"

  release:
    name: Release ${{ matrix.arch }}-${{ matrix.branch }}
    needs: get-version
    runs-on: ubuntu-latest
    continue-on-error: true
    strategy:
      fail-fast: false
      matrix:
        arch:
          - x86_64
        branch:
          - ${{ inputs.releases_branch }}

    steps:
      - name: Checkout build repo
        uses: actions/checkout@v4

      - name: Download SDK if cache miss
        run: |
          set -e
          curl -SLk --retry 3 "https://github.com/tes-rep/tes-build/releases/download/SDK2/15.tar.bz2" -o /tmp/SDK.tar.bz2
          tar -xjf /tmp/SDK.tar.bz2 -C /tmp
          mv /tmp/OpenWrt-SDK-* $GITHUB_WORKSPACE/SNAPSDK

      - name: Clone luci-app-netmon
        run: |
          set -e
          cd "$GITHUB_WORKSPACE/SNAPSDK/package"
          rm -rf ${{ inputs.nama }}
          git clone --depth 1 --branch master --filter=blob:none --sparse ${{ inputs.url }} ${{ inputs.nama }}
          cd ${{ inputs.nama }} && git sparse-checkout set ${{ inputs.nama }}

      - name: Compile package
        run: |
          set -e
          cd "$GITHUB_WORKSPACE/SNAPSDK"
          make package/${{ inputs.nama }}/compile V=99

      - name: Collect artifacts
        run: |
          mkdir -p ${{ github.workspace }}/release-artifacts
          find $GITHUB_WORKSPACE/SNAPSDK/bin/packages -name "${{ inputs.nama }}*.ipk" -exec cp {} ${{ github.workspace }}/release-artifacts/ \; || true
          find $GITHUB_WORKSPACE/SNAPSDK/bin/targets -name "${{ inputs.nama }}*.ipk" -exec cp {} ${{ github.workspace }}/release-artifacts/ \; || true
          echo "Contents of release-artifacts directory:"
          ls -la ${{ github.workspace }}/release-artifacts/

      - name: Upload release artifacts
        uses: softprops/action-gh-release@v2
        with:
          tag_name: "v${{ needs.get-version.outputs.version }}"
          files: |
            ${{ github.workspace }}/release-artifacts/*
