name: Build multiple ipk

on:
  workflow_dispatch:
    inputs:
      nama:
        description: "Daftar paket (pisahkan dengan spasi, contoh: luci-app-netdata luci-app-ttyd)"
        required: true
        default: "luci-app-netdata luci-app-ttyd"

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Download OpenWrt SDK
        run: |
          curl -SLk --retry 3 "https://github.com/tes-rep/tes-build/releases/download/SDK2/stabil.tar.zst" -o /tmp/SNAPSDK.tar.zst
          tar --zstd -xf /tmp/SNAPSDK.tar.zst -C /tmp
          mv /tmp/openwrt-sdk-* SNAPSDK

      - name: Copy custom packages
        run: |
          mkdir -p SNAPSDK/package/custom
          for pkg in ${{ inputs.nama }}; do
            echo "===> Copy $pkg"
            cp -r "$pkg" SNAPSDK/package/custom/ || true
          done

      - name: Build packages
        run: |
          cd SNAPSDK
          make defconfig
          for pkg in ${{ inputs.nama }}; do
            echo "===> Build $pkg"
            make package/$pkg/compile V=s || true
          done

      - name: Collect artifacts
        run: |
          mkdir -p release-artifacts
          cp -vf SNAPSDK/bin/packages/*/*/*.ipk release-artifacts/ 2>/dev/null || true
          cp -vf SNAPSDK/bin/targets/*/*/packages/*.ipk release-artifacts/ 2>/dev/null || true
          echo "===> Semua file IPK terkumpul:"
          ls -la release-artifacts/ || true

      - name: Upload artifacts (Actions)
        uses: actions/upload-artifact@v4
        with:
          name: houjie-ipk
          path: release-artifacts/*.ipk

      - name: Install GitHub CLI
        run: |
          sudo apt-get update
          sudo apt-get install -y gh

      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: build-${{ github.run_number }}
          release_name: "Build paket: ${{ inputs.nama }} #${{ github.run_number }}"
          draft: false
          prerelease: false

      - name: Upload Release Assets (per file)
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          for file in release-artifacts/*.ipk; do
            echo "===> Upload $file"
            gh release upload build-${{ github.run_number }} "$file" --clobber
          done
