name: Build multiple ipk (matrix dynamic)

on:
  workflow_dispatch:
    inputs:
      nama:
        description: "Daftar paket (pisahkan dengan spasi, contoh: luci-app-netdata luci-app-ttyd)"
        required: true
        default: "luci-app-netmonitor luci-theme-hj luci-app-netmon"

jobs:
  set-matrix:
    runs-on: ubuntu-22.04
    outputs:
      pkgs: ${{ steps.set.outputs.pkgs }}
    steps:
      - name: Parse input to JSON array
        id: set
        run: |
          arr=$(jq -c -R 'split(" ")' <<< "${{ inputs.nama }}")
          echo "pkgs=$arr" >> $GITHUB_OUTPUT
        shell: bash

  build:
    needs: set-matrix
    runs-on: ubuntu-22.04
    strategy:
      matrix:
        pkg: ${{ fromJson(needs.set-matrix.outputs.pkgs) }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Download OpenWrt SDK
        run: |
          curl -SLk --retry 3 "https://github.com/tes-rep/tes-build/releases/download/SDK2/stabil.tar.zst" -o /tmp/SNAPSDK.tar.zst
          tar --zstd -xf /tmp/SNAPSDK.tar.zst -C /tmp
          mv /tmp/openwrt-sdk-* SNAPSDK
      - name: Update feeds
        run: |
          cd SNAPSDK
          ./scripts/feeds update -a
          ./scripts/feeds install -a
      - name: Copy custom package
        run: |
          mkdir -p SNAPSDK/package/custom
          cp -r ${{ matrix.pkg }} SNAPSDK/package/custom/

      - name: Build package
        run: |
          cd SNAPSDK
          make defconfig
          make package/${{ matrix.pkg }}/compile V=s

      - name: Collect artifacts
        run: |
          mkdir -p release-artifacts
          cp -vf SNAPSDK/bin/packages/*/*/${{ matrix.pkg }}*.ipk release-artifacts/ 2>/dev/null || true
          cp -vf SNAPSDK/bin/targets/*/*/packages/${{ matrix.pkg }}*.ipk release-artifacts/ 2>/dev/null || true
          echo "===> IPK ${{ matrix.pkg }}:"
          ls -la release-artifacts/ || true

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.pkg }}
          path: release-artifacts/*.ipk

  release:
    needs: build
    runs-on: ubuntu-22.04
    permissions:
      contents: write
    steps:
      - name: Install GitHub CLI
        run: |
          sudo apt-get update
          sudo apt-get install -y gh

      - name: Download all artifacts
        uses: actions/download-artifact@v4
        with:
          path: all-artifacts

      - name: Upload ke Release
        id: upload_release2
        uses: softprops/action-gh-release@v1
        with:
          tag_name: build_ipk
          name: "build_ipk"
          body: |
            - Build IPK & APK
          files: all-artifacts/**/*.ipk
          prerelease: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}     
