name: Build luci-app-openclash (vernesong dev)

on:
  workflow_dispatch:
  schedule:
    - cron: "0 */6 * * *"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    # 4. ==================== BUILD SDK SNAPSHOT (APK) ====================
    - name: Download & Ekstrak SDK Snapshot
      run: |
        mkdir -p /tmp/sdk_snap
        BASE_URL="https://downloads.openwrt.org/snapshots/targets/x86/64"
        SDK_NAME=$(curl -s $BASE_URL/ | grep -oE 'openwrt-sdk-x86-64[^"]+\.tar\.zst' | head -n 1)
        curl -SLk "$BASE_URL/$SDK_NAME" -o /tmp/SNAPSDK.tar.zst
        tar --zstd -xf /tmp/SNAPSDK.tar.zst -C /tmp/sdk_snap
        mv /tmp/sdk_snap/openwrt-sdk-* $GITHUB_WORKSPACE/SNAPSDK

    - name: Clone luci-app-openclash (APK)
      run: |
        cd $GITHUB_WORKSPACE/SNAPSDK/package
        git clone --depth 1 --branch dev --filter=blob:none --sparse https://github.com/vernesong/OpenClash luci-app-openclash
        cd luci-app-openclash && git sparse-checkout set luci-app-openclash

   

    - name: Compile luci-app-openclash (APK)
      run: |
        cd $GITHUB_WORKSPACE/SNAPSDK
        make defconfig
        make package/luci-app-openclash/luci-app-openclash/compile V=99
        find bin/ -type f -name "luci-app-openclash*.apk" -exec cp {} $GITHUB_WORKSPACE/release/luci-app-openclash-${LATEST_VER}.apk \;

    - name: Bersihkan SDK snapshot
      run: rm -rf $GITHUB_WORKSPACE/SNAPSDK /tmp/sdk_snap /tmp/SNAPSDK.tar.zst

    - name: Upload to Release
      uses: softprops/action-gh-release@v1
      with:
        tag_name: v${{ env.LATEST_VER }}
        name: "v${{ env.LATEST_VER }}"
        files: release/*
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
