name: Build multiple ipk (matrix dynamic)2

on:
  workflow_dispatch:
    inputs:
      nama:
        description: "Daftar paket (pisahkan dengan spasi, contoh: luci-app-netdata luci-app-ttyd)"
        required: true
        default: "luci-app-netmonitor luci-theme-hj luci-app-netmon"

jobs:
  set-matrix:
    runs-on: ubuntu-22.04
    outputs:
      pkgs: ${{ steps.set.outputs.pkgs }}
    steps:
      - name: Parse input to JSON array
        id: set
        run: |
          arr=$(jq -c -R 'split(" ")' <<< "${{ inputs.nama }}")
          echo "pkgs=$arr" >> $GITHUB_OUTPUT
        shell: bash

  build:
    needs: set-matrix
    runs-on: ubuntu-22.04
    strategy:
      matrix:
        pkg: ${{ fromJson(needs.set-matrix.outputs.pkgs) }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Download OpenWrt SDK
        run: |
          curl -SLk --retry 3 "https://github.com/tes-rep/tes-build/releases/download/SDK2/stabil.tar.zst" -o /tmp/SNAPSDK.tar.zst
          tar --zstd -xf /tmp/SNAPSDK.tar.zst -C /tmp
          mv /tmp/openwrt-sdk-* $GITHUB_WORKSPACE/SNAPSDK

      - name: Copy custom package
        run: |
          cp -r ${{ matrix.pkg }} $GITHUB_WORKSPACE/SNAPSDK/package/

      - name: Build package
        run: |
          cd $GITHUB_WORKSPACE/SNAPSDK
          make defconfig
          make package/${{ matrix.pkg }}/compile V=s
          find bin/ -type f -name "${{ matrix.pkg }}*.ipk" -exec cp {} $GITHUB_WORKSPACE/release/${{ matrix.pkg }}.apk \;

  
      - name: Upload to Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: v${{ env.LATEST_VER }}
          name: "v${{ env.LATEST_VER }}"
          files: release/*
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
