name: Build luci ipk

on:
  workflow_dispatch:
    inputs:
      nama:
        description: "Nama paket (contoh: luci-app-netdata)"
        required: true
        default: "luci-app-netdata"

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Download OpenWrt SDK
        run: |
          curl -SLk --retry 3 "https://github.com/tes-rep/tes-build/releases/download/SDK2/stabil.tar.zst" -o /tmp/SNAPSDK.tar.zst
          tar --zstd -xf /tmp/SNAPSDK.tar.zst -C /tmp
          mv /tmp/openwrt-sdk-* SNAPSDK

      - name: Copy custom package
        run: |
          mkdir -p SNAPSDK/package/custom
          cp -r ${{ inputs.nama }} SNAPSDK/package/custom/

      - name: Build package
        run: |
          cd SNAPSDK
          make defconfig
          make package/${{ inputs.nama }}/compile V=s

      - name: Collect artifacts
        run: |
          mkdir -p release-artifacts
          cp -vf SNAPSDK/bin/packages/*/*/${{ inputs.nama }}*.ipk release-artifacts/ 2>/dev/null || true
          cp -vf SNAPSDK/bin/targets/*/*/packages/${{ inputs.nama }}*.ipk release-artifacts/ 2>/dev/null || true
          echo "===> Daftar file IPK:"
          ls -la release-artifacts/ || true

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: houjie-ipk
          path: release-artifacts/*.ipk

      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: build-${{ github.run_number }}
          release_name: "Build ${{ inputs.nama }} #${{ github.run_number }}"
          draft: false
          prerelease: false

      - name: Upload Release Assets
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: release-artifacts/*.ipk
          asset_name: ${{ inputs.nama }}.ipk
          asset_content_type: application/octet-stream
